services:
- type: web
  name: keepy
  env: node
  plan: free
  buildCommand: 'npm install --force'
  startCommand: 'npm run start'
  envVars:
  - key: DATABASE_URL
    value: 'postgresql://note_db_dx96_user:0u7voGulrA6ubWaH6VEXlOvd3XT31DUI@dpg-cqf0loogph6c73b314i0-a.frankfurt-postgres.render.com/note_db_dx96',

